### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jackocnr** [Ulyanov-programmer/grunt-sharp-optimize#1]
Hi there, thanks for putting this project together! I've just installed it with npm and tried to run the task and I'm getting the following error:

> Loading "index.js" tasks...ERROR
>> Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/jack/workspace/intl-tel-input/node_modules/grunt-sharp-optimize/node_modules/chalk/source/index.js from /Users/jack/workspace/intl-tel-input/node_modules/grunt-sharp-optimize/tasks/index.js not supported.
>> Instead change the require of /Users/jack/workspace/intl-tel-input/node_modules/grunt-sharp-optimize/node_modules/chalk/source/index.js in /Users/jack/workspace/intl-tel-input/node_modules/grunt-sharp-optimize/tasks/index.js to a dynamic import() which is available in all CommonJS modules.

Do you have any ideas? I'm using [load-grunt-config](https://github.com/firstandthird/load-grunt-config) to assemble the config object, but AFAICS this shouldn't have any effect - it just allows you to use separate config files, and then bundles them together into a single config object when running grunt tasks.

**Comment by Ulyanov-programmer** [comment]
I did everything right - I did not take into account one thing, the `chalk` package version 5 is an ESM module.

It worked fine for me because I used `esm-fix`, but I understand you don't have it.
Yeah, well, I'll deal with this problem in the near time, I think switching to chalk version 4 will fix the problem.

**Comment by Ulyanov-programmer** [comment]
So, I've made some [changes](https://github.com/Ulyanov-programmer/grunt-sharp-optimize/commit/9e31ddb11a6c690a15f32b33378126e769e5af80). 

If it's not difficult for you, please try the modified version. To do this, install it by specifying it in the `package.json`: 
`"grunt-sharp-optimize": "github:Ulyanov-programmer/grunt-sharp-optimize#main",`

And reassemble the packages.

**Comment by Ulyanov-programmer** [comment]
Could you test the updated package? This will allow me to release the update more confidently.

**Comment by jackocnr** [comment]
Thanks for your work on this. I'm currently away, but should be able to test this next week.

**Comment by Ulyanov-programmer** [comment]
Hello! Perhaps it's time to remind you.

**Comment by jackocnr** [comment]
This change fixed the issue for me, thanks 👍

**Comment by Ulyanov-programmer** [comment]
Wait for the plugin update soon!
